---
- name: EC2 Disk Utilization via SSM with Roles
  hosts: accounts
  gather_facts: no
  roles:
    - assume_role
    - gather_ec2
    - run_ssm
    - collect_disk

- name: Consolidate all reports and upload to S3
  hosts: localhost
  gather_facts: no
  roles:
    - consolidate_report